---
- hosts: all
  become: true
  tasks:
   - name: Creating the files
     file:
      path: /tmp/mithuntechnologies.sh
      owner: ansible
      group: ansible
      mode: 0777
      state: touch
...