---
- hosts: all
  gather_facts: no
  tasks:
   - name: Changing the Permissions
     file:
      path: /tmp/mithuntechnologies.sh
      mode: 1777
   - name: Creating the hardlink
     file: 
      src: /tmp/mithuntechnologies.sh
      dest: /tmp/mithunhard.txt
      state: hard
...