---
- hosts: all
  gather_facts: no
  become: true
  tasks:
   - name: Creating the users
     user:
      name: "{{item}}"
     with_ites:
      - bhaskar
      - balaji
      - mithun
      - ruthvik
...