---
- hosts: all
  become: true
  gather_facts: no
  vars:
   companyName: MSS
   location: America
   contact: 9980923226
  tasks:
   - name: Install Apache HTTP Server
     tags:
      - install
     yum:
      name: httpd
      state: latest
   - name: Enable the service
     systemd:
      name: httpd
      enabled: true
   - name: Copy index.html
     tags: 
      - copy
     template:
      src: index.html
      dest: /var/www/html/index.html
   - name: Start the Apache HTTP Server
     tags: 
      - start
      - install
     service:
      name: httpd
      state: started
...