---
- hosts: all
  gather_facts: no
  become: true
  vars_files:
   - vars.yaml
  vars:
    companyName: MSS
    location: America
    contact: 9980923226
  tasks:
   - name: Install Apache HTTP Server
     yum:
      name: httpd
      state: latest
   - name: Enable the service
     systemd:
      name: httpd
      enabled: true
   - name: Copy index.html
     template:
      src: index.html
      dest: /var/www/html/index.html
   - name: Start the Apache HTTP Server
     service:
      name: httpd
      state: started
...